services:
  mongodb:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: m321_app
      MONGO_INITDB_ROOT_USERNAME: m321_app
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo_pass
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo_volume:/data/db
      - mongo_volume:/data/configdb
    secrets:
      - mongo_pass

  keycloak:
    image: quay.io/keycloak/keycloak:26.2.4
    container_name: keycloak
    entrypoint: ["/opt/keycloak/start_keycloak.sh"]
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME : admin
      # KC_BOOTSTRAP_ADMIN_PASSWORD_FILE: /run/secrets/keycloak_admin - gibt es so nicht -> wird in start_keycloak.sh gesetzt
      KC_DB: dev-mem
    ports:
      - "${KEYCLOAK_PORT}:8080"
    volumes:
      - ./keycloak:/tmp/keycloak/
      - ./scripts/start_keycloak.sh:/opt/keycloak/start_keycloak.sh
    secrets:
      - keycloak_secret
      - keycloak_admin
      - keycloak_test_user

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: always
    ports:
      - "1883:1883" # MQTT
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - mosquitto_volume:/mosquitto/data
    secrets:
      - mosquitto_user

  m321_app:
    container_name: m321_app
    build: ./app
    restart: always
    environment:
      REBUILD_INDEXES: true
      RUST_LOG: info
      MONGO_HOST: mongodb
      MONGO_PORT: ${MONGO_PORT}
      MONGO_DATABASE: m321_app
      MONGO_USERNAME: m321_app
      MONGO_PASSWORD_FILE: /run/secrets/mongo_pass
      SESSION_SECRET_FILE: /run/secrets/session_secret
      KEYCLOAK_SECRET_FILE: /run/secrets/keycloak_secret
      KEYCLOAK_HOST: keycloak
      KEYCLOAK_PORT: ${KEYCLOAK_PORT}
      KEYCLOAK_REALM: m321
      KEYCLOAK_CLIENT_ID: actix-app
      NGINX_PORT: ${NGINX_PORT}
    ports:
      - "80" # only visible to other containers (nginx)
    depends_on:
      - mongodb
      - keycloak
      - mosquitto
    secrets:
      - mongo_pass
      - session_secret
      - keycloak_secret

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - m321_app

volumes:
  mongo_volume:
  mosquitto_volume:

secrets:
  mongo_pass:
    file: ./secrets/mongo_pass.txt
  session_secret:
    file: ./secrets/session_secret.txt
  keycloak_secret:
    file: ./secrets/keycloak_secret.txt
  keycloak_admin:
    file: ./secrets/keycloak_admin.txt
  keycloak_test_user:
    file: ./secrets/keycloak_test_user.txt
  mosquitto_user:
    file: ./secrets/mosquitto_user.txt
